apiVersion: v1
kind: ConfigMap
metadata:
  name: qr-cafe-config
  namespace: qr-cafe
data:
  NODE_ENV: "production"
  PORT: "5000"
  MONGODB_URI: "mongodb+srv://appuy8164:RqxOW1X2Z67DrebQ@cafeqr.crpmnjk.mongodb.net/?retryWrites=true&w=majority&appName=cafeqr"
---
apiVersion: v1
kind: Secret
metadata:
  name: qr-cafe-secrets
  namespace: qr-cafe
type: Opaque
stringData:
  JWT_SECRET: "your_production_jwt_secret_here_make_it_very_complex"
