name: Backend CI/CD

on:
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Lint (optional)
        run: npm run lint || echo "Lint failed"

      - name: Build Docker image (optional)
        run: docker build -t cafeqr-backend .

      # Optional: Push image to Docker Hub or GHCR
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #
      # - name: Push to Docker Hub
      #   run: docker tag cafeqr-backend your-dockerhub-username/cafeqr-backend:latest && docker push your-dockerhub-username/cafeqr-backend:latest
